/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordImport } from './routes/(auth)/reset-password'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as auth500Import } from './routes/(auth)/500'
import { Route as authTaikhoanIndexImport } from './routes/(auth)/taikhoan/index'
import { Route as authDatHangIndexImport } from './routes/(auth)/dat-hang/index'
import { Route as AuthenticatedVoucherCreateImport } from './routes/_authenticated/voucher/create'
import { Route as AuthenticatedProductWifiImport } from './routes/_authenticated/product/wifi'
import { Route as AuthenticatedProductSimImport } from './routes/_authenticated/product/sim'
import { Route as AuthenticatedProductScreenImport } from './routes/_authenticated/product/screen'
import { Route as AuthenticatedProductRomImport } from './routes/_authenticated/product/rom'
import { Route as AuthenticatedProductResolutionImport } from './routes/_authenticated/product/resolution'
import { Route as AuthenticatedProductRearCameraImport } from './routes/_authenticated/product/rear-camera'
import { Route as AuthenticatedProductRamImport } from './routes/_authenticated/product/ram'
import { Route as AuthenticatedProductOsImport } from './routes/_authenticated/product/os'
import { Route as AuthenticatedProductImeiImport } from './routes/_authenticated/product/imei'
import { Route as AuthenticatedProductFrontCameraImport } from './routes/_authenticated/product/front-camera'
import { Route as AuthenticatedProductCreateProductImport } from './routes/_authenticated/product/create-product'
import { Route as AuthenticatedProductColorImport } from './routes/_authenticated/product/color'
import { Route as AuthenticatedProductChipImport } from './routes/_authenticated/product/chip'
import { Route as AuthenticatedProductCategoryImport } from './routes/_authenticated/product/category'
import { Route as AuthenticatedProductCardImport } from './routes/_authenticated/product/card'
import { Route as AuthenticatedProductBrandImport } from './routes/_authenticated/product/brand'
import { Route as AuthenticatedProductBluetoothImport } from './routes/_authenticated/product/bluetooth'
import { Route as AuthenticatedProductBatteryImport } from './routes/_authenticated/product/battery'
import { Route as AuthenticatedHoadonHoadonchitietImport } from './routes/_authenticated/hoadon/hoadonchitiet'
import { Route as authTracuudonhangThongTinImport } from './routes/(auth)/tra_cuu_don_hang/thong-tin'
import { Route as authProductIdImport } from './routes/(auth)/product.$id'
import { Route as AuthenticatedTaikhoanNhanvienIndexImport } from './routes/_authenticated/taikhoan/nhanvien/index'
import { Route as AuthenticatedTaikhoanKhachhangIndexImport } from './routes/_authenticated/taikhoan/khachhang/index'
import { Route as authTaikhoanThongTinCaNhanIndexImport } from './routes/(auth)/taikhoan/thong-tin-ca-nhan/index'
import { Route as authTaikhoanDonHangCuaToiIndexImport } from './routes/(auth)/taikhoan/don-hang-cua-toi/index'
import { Route as AuthenticatedProductIdProductDetailImport } from './routes/_authenticated/product/$id.product-detail'

// Create Virtual Routes

const authIndexLazyImport = createFileRoute('/(auth)/')()
const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedSettingsRouteLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedVoucherIndexLazyImport = createFileRoute(
  '/_authenticated/voucher/',
)()
const AuthenticatedSettingsIndexLazyImport = createFileRoute(
  '/_authenticated/settings/',
)()
const AuthenticatedSaleIndexLazyImport = createFileRoute(
  '/_authenticated/sale/',
)()
const AuthenticatedQuanLyLienHeIndexLazyImport = createFileRoute(
  '/_authenticated/quan-ly-lien-he/',
)()
const AuthenticatedProductIndexLazyImport = createFileRoute(
  '/_authenticated/product/',
)()
const AuthenticatedHoadonIndexLazyImport = createFileRoute(
  '/_authenticated/hoadon/',
)()
const AuthenticatedHelpCenterIndexLazyImport = createFileRoute(
  '/_authenticated/help-center/',
)()
const AuthenticatedDashboardIndexLazyImport = createFileRoute(
  '/_authenticated/dashboard/',
)()
const AuthenticatedChatsIndexLazyImport = createFileRoute(
  '/_authenticated/chats/',
)()
const AuthenticatedBanhangIndexLazyImport = createFileRoute(
  '/_authenticated/banhang/',
)()
const authTracuudonhangIndexLazyImport = createFileRoute(
  '/(auth)/tra_cuu_don_hang/',
)()
const authLienHeIndexLazyImport = createFileRoute('/(auth)/lien-he/')()
const authGioHangIndexLazyImport = createFileRoute('/(auth)/gio-hang/')()
const authDienthoaiIndexLazyImport = createFileRoute('/(auth)/dienthoai/')()
const authChinhSachCuaCuaHangIndexLazyImport = createFileRoute(
  '/(auth)/chinh-sach-cua-cua-hang/',
)()
const AuthenticatedSettingsNotificationsLazyImport = createFileRoute(
  '/_authenticated/settings/notifications',
)()
const AuthenticatedSettingsDisplayLazyImport = createFileRoute(
  '/_authenticated/settings/display',
)()
const AuthenticatedSettingsAppearanceLazyImport = createFileRoute(
  '/_authenticated/settings/appearance',
)()
const AuthenticatedSettingsAccountLazyImport = createFileRoute(
  '/_authenticated/settings/account',
)()
const authDatHangPaymentResultLazyImport = createFileRoute(
  '/(auth)/dat-hang/payment-result',
)()
const authTaikhoanDonHangCuaToiThongTinIndexLazyImport = createFileRoute(
  '/(auth)/taikhoan/don-hang-cua-toi/thong-tin/',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const authIndexLazyRoute = authIndexLazyImport
  .update({
    id: '/(auth)/',
    path: '/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/index.lazy').then((d) => d.Route))

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authResetPasswordRoute = authResetPasswordImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedVoucherIndexLazyRoute =
  AuthenticatedVoucherIndexLazyImport.update({
    id: '/voucher/',
    path: '/voucher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/voucher/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsIndexLazyRoute =
  AuthenticatedSettingsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSaleIndexLazyRoute = AuthenticatedSaleIndexLazyImport.update(
  {
    id: '/sale/',
    path: '/sale/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/sale/index.lazy').then((d) => d.Route),
)

const AuthenticatedQuanLyLienHeIndexLazyRoute =
  AuthenticatedQuanLyLienHeIndexLazyImport.update({
    id: '/quan-ly-lien-he/',
    path: '/quan-ly-lien-he/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/quan-ly-lien-he/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProductIndexLazyRoute =
  AuthenticatedProductIndexLazyImport.update({
    id: '/product/',
    path: '/product/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product/index.lazy').then((d) => d.Route),
  )

const AuthenticatedHoadonIndexLazyRoute =
  AuthenticatedHoadonIndexLazyImport.update({
    id: '/hoadon/',
    path: '/hoadon/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/hoadon/index.lazy').then((d) => d.Route),
  )

const AuthenticatedHelpCenterIndexLazyRoute =
  AuthenticatedHelpCenterIndexLazyImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/help-center/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDashboardIndexLazyRoute =
  AuthenticatedDashboardIndexLazyImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/index.lazy').then((d) => d.Route),
  )

const AuthenticatedChatsIndexLazyRoute =
  AuthenticatedChatsIndexLazyImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/chats/index.lazy').then((d) => d.Route),
  )

const AuthenticatedBanhangIndexLazyRoute =
  AuthenticatedBanhangIndexLazyImport.update({
    id: '/banhang/',
    path: '/banhang/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/banhang/index.lazy').then((d) => d.Route),
  )

const authTracuudonhangIndexLazyRoute = authTracuudonhangIndexLazyImport
  .update({
    id: '/(auth)/tra_cuu_don_hang/',
    path: '/tra_cuu_don_hang/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/tra_cuu_don_hang/index.lazy').then((d) => d.Route),
  )

const authLienHeIndexLazyRoute = authLienHeIndexLazyImport
  .update({
    id: '/(auth)/lien-he/',
    path: '/lien-he/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/lien-he/index.lazy').then((d) => d.Route))

const authGioHangIndexLazyRoute = authGioHangIndexLazyImport
  .update({
    id: '/(auth)/gio-hang/',
    path: '/gio-hang/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/gio-hang/index.lazy').then((d) => d.Route),
  )

const authDienthoaiIndexLazyRoute = authDienthoaiIndexLazyImport
  .update({
    id: '/(auth)/dienthoai/',
    path: '/dienthoai/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/dienthoai/index.lazy').then((d) => d.Route),
  )

const authChinhSachCuaCuaHangIndexLazyRoute =
  authChinhSachCuaCuaHangIndexLazyImport
    .update({
      id: '/(auth)/chinh-sach-cua-cua-hang/',
      path: '/chinh-sach-cua-cua-hang/',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(auth)/chinh-sach-cua-cua-hang/index.lazy').then(
        (d) => d.Route,
      ),
    )

const authTaikhoanIndexRoute = authTaikhoanIndexImport.update({
  id: '/(auth)/taikhoan/',
  path: '/taikhoan/',
  getParentRoute: () => rootRoute,
} as any)

const authDatHangIndexRoute = authDatHangIndexImport.update({
  id: '/(auth)/dat-hang/',
  path: '/dat-hang/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsNotificationsLazyRoute =
  AuthenticatedSettingsNotificationsLazyImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsDisplayLazyRoute =
  AuthenticatedSettingsDisplayLazyImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/display.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAppearanceLazyRoute =
  AuthenticatedSettingsAppearanceLazyImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/appearance.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAccountLazyRoute =
  AuthenticatedSettingsAccountLazyImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )

const authDatHangPaymentResultLazyRoute = authDatHangPaymentResultLazyImport
  .update({
    id: '/(auth)/dat-hang/payment-result',
    path: '/dat-hang/payment-result',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/dat-hang/payment-result.lazy').then((d) => d.Route),
  )

const AuthenticatedVoucherCreateRoute = AuthenticatedVoucherCreateImport.update(
  {
    id: '/voucher/create',
    path: '/voucher/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedProductWifiRoute = AuthenticatedProductWifiImport.update({
  id: '/product/wifi',
  path: '/product/wifi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedProductSimRoute = AuthenticatedProductSimImport.update({
  id: '/product/sim',
  path: '/product/sim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedProductScreenRoute = AuthenticatedProductScreenImport.update(
  {
    id: '/product/screen',
    path: '/product/screen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedProductRomRoute = AuthenticatedProductRomImport.update({
  id: '/product/rom',
  path: '/product/rom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedProductResolutionRoute =
  AuthenticatedProductResolutionImport.update({
    id: '/product/resolution',
    path: '/product/resolution',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedProductRearCameraRoute =
  AuthenticatedProductRearCameraImport.update({
    id: '/product/rear-camera',
    path: '/product/rear-camera',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedProductRamRoute = AuthenticatedProductRamImport.update({
  id: '/product/ram',
  path: '/product/ram',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedProductOsRoute = AuthenticatedProductOsImport.update({
  id: '/product/os',
  path: '/product/os',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedProductImeiRoute = AuthenticatedProductImeiImport.update({
  id: '/product/imei',
  path: '/product/imei',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedProductFrontCameraRoute =
  AuthenticatedProductFrontCameraImport.update({
    id: '/product/front-camera',
    path: '/product/front-camera',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedProductCreateProductRoute =
  AuthenticatedProductCreateProductImport.update({
    id: '/product/create-product',
    path: '/product/create-product',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedProductColorRoute = AuthenticatedProductColorImport.update({
  id: '/product/color',
  path: '/product/color',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedProductChipRoute = AuthenticatedProductChipImport.update({
  id: '/product/chip',
  path: '/product/chip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedProductCategoryRoute =
  AuthenticatedProductCategoryImport.update({
    id: '/product/category',
    path: '/product/category',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedProductCardRoute = AuthenticatedProductCardImport.update({
  id: '/product/card',
  path: '/product/card',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedProductBrandRoute = AuthenticatedProductBrandImport.update({
  id: '/product/brand',
  path: '/product/brand',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedProductBluetoothRoute =
  AuthenticatedProductBluetoothImport.update({
    id: '/product/bluetooth',
    path: '/product/bluetooth',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedProductBatteryRoute =
  AuthenticatedProductBatteryImport.update({
    id: '/product/battery',
    path: '/product/battery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedHoadonHoadonchitietRoute =
  AuthenticatedHoadonHoadonchitietImport.update({
    id: '/hoadon/hoadonchitiet',
    path: '/hoadon/hoadonchitiet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const authTracuudonhangThongTinRoute = authTracuudonhangThongTinImport.update({
  id: '/(auth)/tra_cuu_don_hang/thong-tin',
  path: '/tra_cuu_don_hang/thong-tin',
  getParentRoute: () => rootRoute,
} as any)

const authProductIdRoute = authProductIdImport.update({
  id: '/(auth)/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedTaikhoanNhanvienIndexRoute =
  AuthenticatedTaikhoanNhanvienIndexImport.update({
    id: '/taikhoan/nhanvien/',
    path: '/taikhoan/nhanvien/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedTaikhoanKhachhangIndexRoute =
  AuthenticatedTaikhoanKhachhangIndexImport.update({
    id: '/taikhoan/khachhang/',
    path: '/taikhoan/khachhang/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const authTaikhoanThongTinCaNhanIndexRoute =
  authTaikhoanThongTinCaNhanIndexImport.update({
    id: '/(auth)/taikhoan/thong-tin-ca-nhan/',
    path: '/taikhoan/thong-tin-ca-nhan/',
    getParentRoute: () => rootRoute,
  } as any)

const authTaikhoanDonHangCuaToiIndexRoute =
  authTaikhoanDonHangCuaToiIndexImport.update({
    id: '/(auth)/taikhoan/don-hang-cua-toi/',
    path: '/taikhoan/don-hang-cua-toi/',
    getParentRoute: () => rootRoute,
  } as any)

const AuthenticatedProductIdProductDetailRoute =
  AuthenticatedProductIdProductDetailImport.update({
    id: '/product/$id/product-detail',
    path: '/product/$id/product-detail',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const authTaikhoanDonHangCuaToiThongTinIndexLazyRoute =
  authTaikhoanDonHangCuaToiThongTinIndexLazyImport
    .update({
      id: '/(auth)/taikhoan/don-hang-cua-toi/thong-tin/',
      path: '/taikhoan/don-hang-cua-toi/thong-tin/',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(auth)/taikhoan/don-hang-cua-toi/thong-tin/index.lazy'
      ).then((d) => d.Route),
    )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/product/$id': {
      id: '/(auth)/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof authProductIdImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/tra_cuu_don_hang/thong-tin': {
      id: '/(auth)/tra_cuu_don_hang/thong-tin'
      path: '/tra_cuu_don_hang/thong-tin'
      fullPath: '/tra_cuu_don_hang/thong-tin'
      preLoaderRoute: typeof authTracuudonhangThongTinImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/hoadon/hoadonchitiet': {
      id: '/_authenticated/hoadon/hoadonchitiet'
      path: '/hoadon/hoadonchitiet'
      fullPath: '/hoadon/hoadonchitiet'
      preLoaderRoute: typeof AuthenticatedHoadonHoadonchitietImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/battery': {
      id: '/_authenticated/product/battery'
      path: '/product/battery'
      fullPath: '/product/battery'
      preLoaderRoute: typeof AuthenticatedProductBatteryImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/bluetooth': {
      id: '/_authenticated/product/bluetooth'
      path: '/product/bluetooth'
      fullPath: '/product/bluetooth'
      preLoaderRoute: typeof AuthenticatedProductBluetoothImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/brand': {
      id: '/_authenticated/product/brand'
      path: '/product/brand'
      fullPath: '/product/brand'
      preLoaderRoute: typeof AuthenticatedProductBrandImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/card': {
      id: '/_authenticated/product/card'
      path: '/product/card'
      fullPath: '/product/card'
      preLoaderRoute: typeof AuthenticatedProductCardImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/category': {
      id: '/_authenticated/product/category'
      path: '/product/category'
      fullPath: '/product/category'
      preLoaderRoute: typeof AuthenticatedProductCategoryImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/chip': {
      id: '/_authenticated/product/chip'
      path: '/product/chip'
      fullPath: '/product/chip'
      preLoaderRoute: typeof AuthenticatedProductChipImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/color': {
      id: '/_authenticated/product/color'
      path: '/product/color'
      fullPath: '/product/color'
      preLoaderRoute: typeof AuthenticatedProductColorImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/create-product': {
      id: '/_authenticated/product/create-product'
      path: '/product/create-product'
      fullPath: '/product/create-product'
      preLoaderRoute: typeof AuthenticatedProductCreateProductImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/front-camera': {
      id: '/_authenticated/product/front-camera'
      path: '/product/front-camera'
      fullPath: '/product/front-camera'
      preLoaderRoute: typeof AuthenticatedProductFrontCameraImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/imei': {
      id: '/_authenticated/product/imei'
      path: '/product/imei'
      fullPath: '/product/imei'
      preLoaderRoute: typeof AuthenticatedProductImeiImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/os': {
      id: '/_authenticated/product/os'
      path: '/product/os'
      fullPath: '/product/os'
      preLoaderRoute: typeof AuthenticatedProductOsImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/ram': {
      id: '/_authenticated/product/ram'
      path: '/product/ram'
      fullPath: '/product/ram'
      preLoaderRoute: typeof AuthenticatedProductRamImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/rear-camera': {
      id: '/_authenticated/product/rear-camera'
      path: '/product/rear-camera'
      fullPath: '/product/rear-camera'
      preLoaderRoute: typeof AuthenticatedProductRearCameraImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/resolution': {
      id: '/_authenticated/product/resolution'
      path: '/product/resolution'
      fullPath: '/product/resolution'
      preLoaderRoute: typeof AuthenticatedProductResolutionImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/rom': {
      id: '/_authenticated/product/rom'
      path: '/product/rom'
      fullPath: '/product/rom'
      preLoaderRoute: typeof AuthenticatedProductRomImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/screen': {
      id: '/_authenticated/product/screen'
      path: '/product/screen'
      fullPath: '/product/screen'
      preLoaderRoute: typeof AuthenticatedProductScreenImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/sim': {
      id: '/_authenticated/product/sim'
      path: '/product/sim'
      fullPath: '/product/sim'
      preLoaderRoute: typeof AuthenticatedProductSimImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/wifi': {
      id: '/_authenticated/product/wifi'
      path: '/product/wifi'
      fullPath: '/product/wifi'
      preLoaderRoute: typeof AuthenticatedProductWifiImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/voucher/create': {
      id: '/_authenticated/voucher/create'
      path: '/voucher/create'
      fullPath: '/voucher/create'
      preLoaderRoute: typeof AuthenticatedVoucherCreateImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/dat-hang/payment-result': {
      id: '/(auth)/dat-hang/payment-result'
      path: '/dat-hang/payment-result'
      fullPath: '/dat-hang/payment-result'
      preLoaderRoute: typeof authDatHangPaymentResultLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/(auth)/dat-hang/': {
      id: '/(auth)/dat-hang/'
      path: '/dat-hang'
      fullPath: '/dat-hang'
      preLoaderRoute: typeof authDatHangIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/taikhoan/': {
      id: '/(auth)/taikhoan/'
      path: '/taikhoan'
      fullPath: '/taikhoan'
      preLoaderRoute: typeof authTaikhoanIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/chinh-sach-cua-cua-hang/': {
      id: '/(auth)/chinh-sach-cua-cua-hang/'
      path: '/chinh-sach-cua-cua-hang'
      fullPath: '/chinh-sach-cua-cua-hang'
      preLoaderRoute: typeof authChinhSachCuaCuaHangIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/dienthoai/': {
      id: '/(auth)/dienthoai/'
      path: '/dienthoai'
      fullPath: '/dienthoai'
      preLoaderRoute: typeof authDienthoaiIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/gio-hang/': {
      id: '/(auth)/gio-hang/'
      path: '/gio-hang'
      fullPath: '/gio-hang'
      preLoaderRoute: typeof authGioHangIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/lien-he/': {
      id: '/(auth)/lien-he/'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof authLienHeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/tra_cuu_don_hang/': {
      id: '/(auth)/tra_cuu_don_hang/'
      path: '/tra_cuu_don_hang'
      fullPath: '/tra_cuu_don_hang'
      preLoaderRoute: typeof authTracuudonhangIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/banhang/': {
      id: '/_authenticated/banhang/'
      path: '/banhang'
      fullPath: '/banhang'
      preLoaderRoute: typeof AuthenticatedBanhangIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/hoadon/': {
      id: '/_authenticated/hoadon/'
      path: '/hoadon'
      fullPath: '/hoadon'
      preLoaderRoute: typeof AuthenticatedHoadonIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/': {
      id: '/_authenticated/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof AuthenticatedProductIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/quan-ly-lien-he/': {
      id: '/_authenticated/quan-ly-lien-he/'
      path: '/quan-ly-lien-he'
      fullPath: '/quan-ly-lien-he'
      preLoaderRoute: typeof AuthenticatedQuanLyLienHeIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/sale/': {
      id: '/_authenticated/sale/'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof AuthenticatedSaleIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/voucher/': {
      id: '/_authenticated/voucher/'
      path: '/voucher'
      fullPath: '/voucher'
      preLoaderRoute: typeof AuthenticatedVoucherIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/product/$id/product-detail': {
      id: '/_authenticated/product/$id/product-detail'
      path: '/product/$id/product-detail'
      fullPath: '/product/$id/product-detail'
      preLoaderRoute: typeof AuthenticatedProductIdProductDetailImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/taikhoan/don-hang-cua-toi/': {
      id: '/(auth)/taikhoan/don-hang-cua-toi/'
      path: '/taikhoan/don-hang-cua-toi'
      fullPath: '/taikhoan/don-hang-cua-toi'
      preLoaderRoute: typeof authTaikhoanDonHangCuaToiIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/taikhoan/thong-tin-ca-nhan/': {
      id: '/(auth)/taikhoan/thong-tin-ca-nhan/'
      path: '/taikhoan/thong-tin-ca-nhan'
      fullPath: '/taikhoan/thong-tin-ca-nhan'
      preLoaderRoute: typeof authTaikhoanThongTinCaNhanIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/taikhoan/khachhang/': {
      id: '/_authenticated/taikhoan/khachhang/'
      path: '/taikhoan/khachhang'
      fullPath: '/taikhoan/khachhang'
      preLoaderRoute: typeof AuthenticatedTaikhoanKhachhangIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/taikhoan/nhanvien/': {
      id: '/_authenticated/taikhoan/nhanvien/'
      path: '/taikhoan/nhanvien'
      fullPath: '/taikhoan/nhanvien'
      preLoaderRoute: typeof AuthenticatedTaikhoanNhanvienIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/taikhoan/don-hang-cua-toi/thong-tin/': {
      id: '/(auth)/taikhoan/don-hang-cua-toi/thong-tin/'
      path: '/taikhoan/don-hang-cua-toi/thong-tin'
      fullPath: '/taikhoan/don-hang-cua-toi/thong-tin'
      preLoaderRoute: typeof authTaikhoanDonHangCuaToiThongTinIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAccountLazyRoute: typeof AuthenticatedSettingsAccountLazyRoute
  AuthenticatedSettingsAppearanceLazyRoute: typeof AuthenticatedSettingsAppearanceLazyRoute
  AuthenticatedSettingsDisplayLazyRoute: typeof AuthenticatedSettingsDisplayLazyRoute
  AuthenticatedSettingsNotificationsLazyRoute: typeof AuthenticatedSettingsNotificationsLazyRoute
  AuthenticatedSettingsIndexLazyRoute: typeof AuthenticatedSettingsIndexLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAccountLazyRoute:
      AuthenticatedSettingsAccountLazyRoute,
    AuthenticatedSettingsAppearanceLazyRoute:
      AuthenticatedSettingsAppearanceLazyRoute,
    AuthenticatedSettingsDisplayLazyRoute:
      AuthenticatedSettingsDisplayLazyRoute,
    AuthenticatedSettingsNotificationsLazyRoute:
      AuthenticatedSettingsNotificationsLazyRoute,
    AuthenticatedSettingsIndexLazyRoute: AuthenticatedSettingsIndexLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedHoadonHoadonchitietRoute: typeof AuthenticatedHoadonHoadonchitietRoute
  AuthenticatedProductBatteryRoute: typeof AuthenticatedProductBatteryRoute
  AuthenticatedProductBluetoothRoute: typeof AuthenticatedProductBluetoothRoute
  AuthenticatedProductBrandRoute: typeof AuthenticatedProductBrandRoute
  AuthenticatedProductCardRoute: typeof AuthenticatedProductCardRoute
  AuthenticatedProductCategoryRoute: typeof AuthenticatedProductCategoryRoute
  AuthenticatedProductChipRoute: typeof AuthenticatedProductChipRoute
  AuthenticatedProductColorRoute: typeof AuthenticatedProductColorRoute
  AuthenticatedProductCreateProductRoute: typeof AuthenticatedProductCreateProductRoute
  AuthenticatedProductFrontCameraRoute: typeof AuthenticatedProductFrontCameraRoute
  AuthenticatedProductImeiRoute: typeof AuthenticatedProductImeiRoute
  AuthenticatedProductOsRoute: typeof AuthenticatedProductOsRoute
  AuthenticatedProductRamRoute: typeof AuthenticatedProductRamRoute
  AuthenticatedProductRearCameraRoute: typeof AuthenticatedProductRearCameraRoute
  AuthenticatedProductResolutionRoute: typeof AuthenticatedProductResolutionRoute
  AuthenticatedProductRomRoute: typeof AuthenticatedProductRomRoute
  AuthenticatedProductScreenRoute: typeof AuthenticatedProductScreenRoute
  AuthenticatedProductSimRoute: typeof AuthenticatedProductSimRoute
  AuthenticatedProductWifiRoute: typeof AuthenticatedProductWifiRoute
  AuthenticatedVoucherCreateRoute: typeof AuthenticatedVoucherCreateRoute
  AuthenticatedBanhangIndexLazyRoute: typeof AuthenticatedBanhangIndexLazyRoute
  AuthenticatedChatsIndexLazyRoute: typeof AuthenticatedChatsIndexLazyRoute
  AuthenticatedDashboardIndexLazyRoute: typeof AuthenticatedDashboardIndexLazyRoute
  AuthenticatedHelpCenterIndexLazyRoute: typeof AuthenticatedHelpCenterIndexLazyRoute
  AuthenticatedHoadonIndexLazyRoute: typeof AuthenticatedHoadonIndexLazyRoute
  AuthenticatedProductIndexLazyRoute: typeof AuthenticatedProductIndexLazyRoute
  AuthenticatedQuanLyLienHeIndexLazyRoute: typeof AuthenticatedQuanLyLienHeIndexLazyRoute
  AuthenticatedSaleIndexLazyRoute: typeof AuthenticatedSaleIndexLazyRoute
  AuthenticatedVoucherIndexLazyRoute: typeof AuthenticatedVoucherIndexLazyRoute
  AuthenticatedProductIdProductDetailRoute: typeof AuthenticatedProductIdProductDetailRoute
  AuthenticatedTaikhoanKhachhangIndexRoute: typeof AuthenticatedTaikhoanKhachhangIndexRoute
  AuthenticatedTaikhoanNhanvienIndexRoute: typeof AuthenticatedTaikhoanNhanvienIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedHoadonHoadonchitietRoute: AuthenticatedHoadonHoadonchitietRoute,
  AuthenticatedProductBatteryRoute: AuthenticatedProductBatteryRoute,
  AuthenticatedProductBluetoothRoute: AuthenticatedProductBluetoothRoute,
  AuthenticatedProductBrandRoute: AuthenticatedProductBrandRoute,
  AuthenticatedProductCardRoute: AuthenticatedProductCardRoute,
  AuthenticatedProductCategoryRoute: AuthenticatedProductCategoryRoute,
  AuthenticatedProductChipRoute: AuthenticatedProductChipRoute,
  AuthenticatedProductColorRoute: AuthenticatedProductColorRoute,
  AuthenticatedProductCreateProductRoute:
    AuthenticatedProductCreateProductRoute,
  AuthenticatedProductFrontCameraRoute: AuthenticatedProductFrontCameraRoute,
  AuthenticatedProductImeiRoute: AuthenticatedProductImeiRoute,
  AuthenticatedProductOsRoute: AuthenticatedProductOsRoute,
  AuthenticatedProductRamRoute: AuthenticatedProductRamRoute,
  AuthenticatedProductRearCameraRoute: AuthenticatedProductRearCameraRoute,
  AuthenticatedProductResolutionRoute: AuthenticatedProductResolutionRoute,
  AuthenticatedProductRomRoute: AuthenticatedProductRomRoute,
  AuthenticatedProductScreenRoute: AuthenticatedProductScreenRoute,
  AuthenticatedProductSimRoute: AuthenticatedProductSimRoute,
  AuthenticatedProductWifiRoute: AuthenticatedProductWifiRoute,
  AuthenticatedVoucherCreateRoute: AuthenticatedVoucherCreateRoute,
  AuthenticatedBanhangIndexLazyRoute: AuthenticatedBanhangIndexLazyRoute,
  AuthenticatedChatsIndexLazyRoute: AuthenticatedChatsIndexLazyRoute,
  AuthenticatedDashboardIndexLazyRoute: AuthenticatedDashboardIndexLazyRoute,
  AuthenticatedHelpCenterIndexLazyRoute: AuthenticatedHelpCenterIndexLazyRoute,
  AuthenticatedHoadonIndexLazyRoute: AuthenticatedHoadonIndexLazyRoute,
  AuthenticatedProductIndexLazyRoute: AuthenticatedProductIndexLazyRoute,
  AuthenticatedQuanLyLienHeIndexLazyRoute:
    AuthenticatedQuanLyLienHeIndexLazyRoute,
  AuthenticatedSaleIndexLazyRoute: AuthenticatedSaleIndexLazyRoute,
  AuthenticatedVoucherIndexLazyRoute: AuthenticatedVoucherIndexLazyRoute,
  AuthenticatedProductIdProductDetailRoute:
    AuthenticatedProductIdProductDetailRoute,
  AuthenticatedTaikhoanKhachhangIndexRoute:
    AuthenticatedTaikhoanKhachhangIndexRoute,
  AuthenticatedTaikhoanNhanvienIndexRoute:
    AuthenticatedTaikhoanNhanvienIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof authIndexLazyRoute
  '/product/$id': typeof authProductIdRoute
  '/tra_cuu_don_hang/thong-tin': typeof authTracuudonhangThongTinRoute
  '/hoadon/hoadonchitiet': typeof AuthenticatedHoadonHoadonchitietRoute
  '/product/battery': typeof AuthenticatedProductBatteryRoute
  '/product/bluetooth': typeof AuthenticatedProductBluetoothRoute
  '/product/brand': typeof AuthenticatedProductBrandRoute
  '/product/card': typeof AuthenticatedProductCardRoute
  '/product/category': typeof AuthenticatedProductCategoryRoute
  '/product/chip': typeof AuthenticatedProductChipRoute
  '/product/color': typeof AuthenticatedProductColorRoute
  '/product/create-product': typeof AuthenticatedProductCreateProductRoute
  '/product/front-camera': typeof AuthenticatedProductFrontCameraRoute
  '/product/imei': typeof AuthenticatedProductImeiRoute
  '/product/os': typeof AuthenticatedProductOsRoute
  '/product/ram': typeof AuthenticatedProductRamRoute
  '/product/rear-camera': typeof AuthenticatedProductRearCameraRoute
  '/product/resolution': typeof AuthenticatedProductResolutionRoute
  '/product/rom': typeof AuthenticatedProductRomRoute
  '/product/screen': typeof AuthenticatedProductScreenRoute
  '/product/sim': typeof AuthenticatedProductSimRoute
  '/product/wifi': typeof AuthenticatedProductWifiRoute
  '/voucher/create': typeof AuthenticatedVoucherCreateRoute
  '/dat-hang/payment-result': typeof authDatHangPaymentResultLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/dat-hang': typeof authDatHangIndexRoute
  '/taikhoan': typeof authTaikhoanIndexRoute
  '/chinh-sach-cua-cua-hang': typeof authChinhSachCuaCuaHangIndexLazyRoute
  '/dienthoai': typeof authDienthoaiIndexLazyRoute
  '/gio-hang': typeof authGioHangIndexLazyRoute
  '/lien-he': typeof authLienHeIndexLazyRoute
  '/tra_cuu_don_hang': typeof authTracuudonhangIndexLazyRoute
  '/banhang': typeof AuthenticatedBanhangIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/dashboard': typeof AuthenticatedDashboardIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/hoadon': typeof AuthenticatedHoadonIndexLazyRoute
  '/product': typeof AuthenticatedProductIndexLazyRoute
  '/quan-ly-lien-he': typeof AuthenticatedQuanLyLienHeIndexLazyRoute
  '/sale': typeof AuthenticatedSaleIndexLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/voucher': typeof AuthenticatedVoucherIndexLazyRoute
  '/product/$id/product-detail': typeof AuthenticatedProductIdProductDetailRoute
  '/taikhoan/don-hang-cua-toi': typeof authTaikhoanDonHangCuaToiIndexRoute
  '/taikhoan/thong-tin-ca-nhan': typeof authTaikhoanThongTinCaNhanIndexRoute
  '/taikhoan/khachhang': typeof AuthenticatedTaikhoanKhachhangIndexRoute
  '/taikhoan/nhanvien': typeof AuthenticatedTaikhoanNhanvienIndexRoute
  '/taikhoan/don-hang-cua-toi/thong-tin': typeof authTaikhoanDonHangCuaToiThongTinIndexLazyRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof authIndexLazyRoute
  '/product/$id': typeof authProductIdRoute
  '/tra_cuu_don_hang/thong-tin': typeof authTracuudonhangThongTinRoute
  '/hoadon/hoadonchitiet': typeof AuthenticatedHoadonHoadonchitietRoute
  '/product/battery': typeof AuthenticatedProductBatteryRoute
  '/product/bluetooth': typeof AuthenticatedProductBluetoothRoute
  '/product/brand': typeof AuthenticatedProductBrandRoute
  '/product/card': typeof AuthenticatedProductCardRoute
  '/product/category': typeof AuthenticatedProductCategoryRoute
  '/product/chip': typeof AuthenticatedProductChipRoute
  '/product/color': typeof AuthenticatedProductColorRoute
  '/product/create-product': typeof AuthenticatedProductCreateProductRoute
  '/product/front-camera': typeof AuthenticatedProductFrontCameraRoute
  '/product/imei': typeof AuthenticatedProductImeiRoute
  '/product/os': typeof AuthenticatedProductOsRoute
  '/product/ram': typeof AuthenticatedProductRamRoute
  '/product/rear-camera': typeof AuthenticatedProductRearCameraRoute
  '/product/resolution': typeof AuthenticatedProductResolutionRoute
  '/product/rom': typeof AuthenticatedProductRomRoute
  '/product/screen': typeof AuthenticatedProductScreenRoute
  '/product/sim': typeof AuthenticatedProductSimRoute
  '/product/wifi': typeof AuthenticatedProductWifiRoute
  '/voucher/create': typeof AuthenticatedVoucherCreateRoute
  '/dat-hang/payment-result': typeof authDatHangPaymentResultLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/dat-hang': typeof authDatHangIndexRoute
  '/taikhoan': typeof authTaikhoanIndexRoute
  '/chinh-sach-cua-cua-hang': typeof authChinhSachCuaCuaHangIndexLazyRoute
  '/dienthoai': typeof authDienthoaiIndexLazyRoute
  '/gio-hang': typeof authGioHangIndexLazyRoute
  '/lien-he': typeof authLienHeIndexLazyRoute
  '/tra_cuu_don_hang': typeof authTracuudonhangIndexLazyRoute
  '/banhang': typeof AuthenticatedBanhangIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/dashboard': typeof AuthenticatedDashboardIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/hoadon': typeof AuthenticatedHoadonIndexLazyRoute
  '/product': typeof AuthenticatedProductIndexLazyRoute
  '/quan-ly-lien-he': typeof AuthenticatedQuanLyLienHeIndexLazyRoute
  '/sale': typeof AuthenticatedSaleIndexLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexLazyRoute
  '/voucher': typeof AuthenticatedVoucherIndexLazyRoute
  '/product/$id/product-detail': typeof AuthenticatedProductIdProductDetailRoute
  '/taikhoan/don-hang-cua-toi': typeof authTaikhoanDonHangCuaToiIndexRoute
  '/taikhoan/thong-tin-ca-nhan': typeof authTaikhoanThongTinCaNhanIndexRoute
  '/taikhoan/khachhang': typeof AuthenticatedTaikhoanKhachhangIndexRoute
  '/taikhoan/nhanvien': typeof AuthenticatedTaikhoanNhanvienIndexRoute
  '/taikhoan/don-hang-cua-toi/thong-tin': typeof authTaikhoanDonHangCuaToiThongTinIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/(auth)/': typeof authIndexLazyRoute
  '/(auth)/product/$id': typeof authProductIdRoute
  '/(auth)/tra_cuu_don_hang/thong-tin': typeof authTracuudonhangThongTinRoute
  '/_authenticated/hoadon/hoadonchitiet': typeof AuthenticatedHoadonHoadonchitietRoute
  '/_authenticated/product/battery': typeof AuthenticatedProductBatteryRoute
  '/_authenticated/product/bluetooth': typeof AuthenticatedProductBluetoothRoute
  '/_authenticated/product/brand': typeof AuthenticatedProductBrandRoute
  '/_authenticated/product/card': typeof AuthenticatedProductCardRoute
  '/_authenticated/product/category': typeof AuthenticatedProductCategoryRoute
  '/_authenticated/product/chip': typeof AuthenticatedProductChipRoute
  '/_authenticated/product/color': typeof AuthenticatedProductColorRoute
  '/_authenticated/product/create-product': typeof AuthenticatedProductCreateProductRoute
  '/_authenticated/product/front-camera': typeof AuthenticatedProductFrontCameraRoute
  '/_authenticated/product/imei': typeof AuthenticatedProductImeiRoute
  '/_authenticated/product/os': typeof AuthenticatedProductOsRoute
  '/_authenticated/product/ram': typeof AuthenticatedProductRamRoute
  '/_authenticated/product/rear-camera': typeof AuthenticatedProductRearCameraRoute
  '/_authenticated/product/resolution': typeof AuthenticatedProductResolutionRoute
  '/_authenticated/product/rom': typeof AuthenticatedProductRomRoute
  '/_authenticated/product/screen': typeof AuthenticatedProductScreenRoute
  '/_authenticated/product/sim': typeof AuthenticatedProductSimRoute
  '/_authenticated/product/wifi': typeof AuthenticatedProductWifiRoute
  '/_authenticated/voucher/create': typeof AuthenticatedVoucherCreateRoute
  '/(auth)/dat-hang/payment-result': typeof authDatHangPaymentResultLazyRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/(auth)/dat-hang/': typeof authDatHangIndexRoute
  '/(auth)/taikhoan/': typeof authTaikhoanIndexRoute
  '/(auth)/chinh-sach-cua-cua-hang/': typeof authChinhSachCuaCuaHangIndexLazyRoute
  '/(auth)/dienthoai/': typeof authDienthoaiIndexLazyRoute
  '/(auth)/gio-hang/': typeof authGioHangIndexLazyRoute
  '/(auth)/lien-he/': typeof authLienHeIndexLazyRoute
  '/(auth)/tra_cuu_don_hang/': typeof authTracuudonhangIndexLazyRoute
  '/_authenticated/banhang/': typeof AuthenticatedBanhangIndexLazyRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexLazyRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexLazyRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/_authenticated/hoadon/': typeof AuthenticatedHoadonIndexLazyRoute
  '/_authenticated/product/': typeof AuthenticatedProductIndexLazyRoute
  '/_authenticated/quan-ly-lien-he/': typeof AuthenticatedQuanLyLienHeIndexLazyRoute
  '/_authenticated/sale/': typeof AuthenticatedSaleIndexLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/_authenticated/voucher/': typeof AuthenticatedVoucherIndexLazyRoute
  '/_authenticated/product/$id/product-detail': typeof AuthenticatedProductIdProductDetailRoute
  '/(auth)/taikhoan/don-hang-cua-toi/': typeof authTaikhoanDonHangCuaToiIndexRoute
  '/(auth)/taikhoan/thong-tin-ca-nhan/': typeof authTaikhoanThongTinCaNhanIndexRoute
  '/_authenticated/taikhoan/khachhang/': typeof AuthenticatedTaikhoanKhachhangIndexRoute
  '/_authenticated/taikhoan/nhanvien/': typeof AuthenticatedTaikhoanNhanvienIndexRoute
  '/(auth)/taikhoan/don-hang-cua-toi/thong-tin/': typeof authTaikhoanDonHangCuaToiThongTinIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/500'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/settings'
    | '/forgot-password'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/product/$id'
    | '/tra_cuu_don_hang/thong-tin'
    | '/hoadon/hoadonchitiet'
    | '/product/battery'
    | '/product/bluetooth'
    | '/product/brand'
    | '/product/card'
    | '/product/category'
    | '/product/chip'
    | '/product/color'
    | '/product/create-product'
    | '/product/front-camera'
    | '/product/imei'
    | '/product/os'
    | '/product/ram'
    | '/product/rear-camera'
    | '/product/resolution'
    | '/product/rom'
    | '/product/screen'
    | '/product/sim'
    | '/product/wifi'
    | '/voucher/create'
    | '/dat-hang/payment-result'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/dat-hang'
    | '/taikhoan'
    | '/chinh-sach-cua-cua-hang'
    | '/dienthoai'
    | '/gio-hang'
    | '/lien-he'
    | '/tra_cuu_don_hang'
    | '/banhang'
    | '/chats'
    | '/dashboard'
    | '/help-center'
    | '/hoadon'
    | '/product'
    | '/quan-ly-lien-he'
    | '/sale'
    | '/settings/'
    | '/voucher'
    | '/product/$id/product-detail'
    | '/taikhoan/don-hang-cua-toi'
    | '/taikhoan/thong-tin-ca-nhan'
    | '/taikhoan/khachhang'
    | '/taikhoan/nhanvien'
    | '/taikhoan/don-hang-cua-toi/thong-tin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/500'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/forgot-password'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/product/$id'
    | '/tra_cuu_don_hang/thong-tin'
    | '/hoadon/hoadonchitiet'
    | '/product/battery'
    | '/product/bluetooth'
    | '/product/brand'
    | '/product/card'
    | '/product/category'
    | '/product/chip'
    | '/product/color'
    | '/product/create-product'
    | '/product/front-camera'
    | '/product/imei'
    | '/product/os'
    | '/product/ram'
    | '/product/rear-camera'
    | '/product/resolution'
    | '/product/rom'
    | '/product/screen'
    | '/product/sim'
    | '/product/wifi'
    | '/voucher/create'
    | '/dat-hang/payment-result'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/dat-hang'
    | '/taikhoan'
    | '/chinh-sach-cua-cua-hang'
    | '/dienthoai'
    | '/gio-hang'
    | '/lien-he'
    | '/tra_cuu_don_hang'
    | '/banhang'
    | '/chats'
    | '/dashboard'
    | '/help-center'
    | '/hoadon'
    | '/product'
    | '/quan-ly-lien-he'
    | '/sale'
    | '/settings'
    | '/voucher'
    | '/product/$id/product-detail'
    | '/taikhoan/don-hang-cua-toi'
    | '/taikhoan/thong-tin-ca-nhan'
    | '/taikhoan/khachhang'
    | '/taikhoan/nhanvien'
    | '/taikhoan/don-hang-cua-toi/thong-tin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/500'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(auth)/'
    | '/(auth)/product/$id'
    | '/(auth)/tra_cuu_don_hang/thong-tin'
    | '/_authenticated/hoadon/hoadonchitiet'
    | '/_authenticated/product/battery'
    | '/_authenticated/product/bluetooth'
    | '/_authenticated/product/brand'
    | '/_authenticated/product/card'
    | '/_authenticated/product/category'
    | '/_authenticated/product/chip'
    | '/_authenticated/product/color'
    | '/_authenticated/product/create-product'
    | '/_authenticated/product/front-camera'
    | '/_authenticated/product/imei'
    | '/_authenticated/product/os'
    | '/_authenticated/product/ram'
    | '/_authenticated/product/rear-camera'
    | '/_authenticated/product/resolution'
    | '/_authenticated/product/rom'
    | '/_authenticated/product/screen'
    | '/_authenticated/product/sim'
    | '/_authenticated/product/wifi'
    | '/_authenticated/voucher/create'
    | '/(auth)/dat-hang/payment-result'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/(auth)/dat-hang/'
    | '/(auth)/taikhoan/'
    | '/(auth)/chinh-sach-cua-cua-hang/'
    | '/(auth)/dienthoai/'
    | '/(auth)/gio-hang/'
    | '/(auth)/lien-he/'
    | '/(auth)/tra_cuu_don_hang/'
    | '/_authenticated/banhang/'
    | '/_authenticated/chats/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/help-center/'
    | '/_authenticated/hoadon/'
    | '/_authenticated/product/'
    | '/_authenticated/quan-ly-lien-he/'
    | '/_authenticated/sale/'
    | '/_authenticated/settings/'
    | '/_authenticated/voucher/'
    | '/_authenticated/product/$id/product-detail'
    | '/(auth)/taikhoan/don-hang-cua-toi/'
    | '/(auth)/taikhoan/thong-tin-ca-nhan/'
    | '/_authenticated/taikhoan/khachhang/'
    | '/_authenticated/taikhoan/nhanvien/'
    | '/(auth)/taikhoan/don-hang-cua-toi/thong-tin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
  authIndexLazyRoute: typeof authIndexLazyRoute
  authProductIdRoute: typeof authProductIdRoute
  authTracuudonhangThongTinRoute: typeof authTracuudonhangThongTinRoute
  authDatHangPaymentResultLazyRoute: typeof authDatHangPaymentResultLazyRoute
  authDatHangIndexRoute: typeof authDatHangIndexRoute
  authTaikhoanIndexRoute: typeof authTaikhoanIndexRoute
  authChinhSachCuaCuaHangIndexLazyRoute: typeof authChinhSachCuaCuaHangIndexLazyRoute
  authDienthoaiIndexLazyRoute: typeof authDienthoaiIndexLazyRoute
  authGioHangIndexLazyRoute: typeof authGioHangIndexLazyRoute
  authLienHeIndexLazyRoute: typeof authLienHeIndexLazyRoute
  authTracuudonhangIndexLazyRoute: typeof authTracuudonhangIndexLazyRoute
  authTaikhoanDonHangCuaToiIndexRoute: typeof authTaikhoanDonHangCuaToiIndexRoute
  authTaikhoanThongTinCaNhanIndexRoute: typeof authTaikhoanThongTinCaNhanIndexRoute
  authTaikhoanDonHangCuaToiThongTinIndexLazyRoute: typeof authTaikhoanDonHangCuaToiThongTinIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  auth500Route: auth500Route,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
  authIndexLazyRoute: authIndexLazyRoute,
  authProductIdRoute: authProductIdRoute,
  authTracuudonhangThongTinRoute: authTracuudonhangThongTinRoute,
  authDatHangPaymentResultLazyRoute: authDatHangPaymentResultLazyRoute,
  authDatHangIndexRoute: authDatHangIndexRoute,
  authTaikhoanIndexRoute: authTaikhoanIndexRoute,
  authChinhSachCuaCuaHangIndexLazyRoute: authChinhSachCuaCuaHangIndexLazyRoute,
  authDienthoaiIndexLazyRoute: authDienthoaiIndexLazyRoute,
  authGioHangIndexLazyRoute: authGioHangIndexLazyRoute,
  authLienHeIndexLazyRoute: authLienHeIndexLazyRoute,
  authTracuudonhangIndexLazyRoute: authTracuudonhangIndexLazyRoute,
  authTaikhoanDonHangCuaToiIndexRoute: authTaikhoanDonHangCuaToiIndexRoute,
  authTaikhoanThongTinCaNhanIndexRoute: authTaikhoanThongTinCaNhanIndexRoute,
  authTaikhoanDonHangCuaToiThongTinIndexLazyRoute:
    authTaikhoanDonHangCuaToiThongTinIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/500",
        "/(auth)/otp",
        "/(auth)/reset-password",
        "/(auth)/sign-in",
        "/(auth)/forgot-password",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503",
        "/(auth)/",
        "/(auth)/product/$id",
        "/(auth)/tra_cuu_don_hang/thong-tin",
        "/(auth)/dat-hang/payment-result",
        "/(auth)/dat-hang/",
        "/(auth)/taikhoan/",
        "/(auth)/chinh-sach-cua-cua-hang/",
        "/(auth)/dienthoai/",
        "/(auth)/gio-hang/",
        "/(auth)/lien-he/",
        "/(auth)/tra_cuu_don_hang/",
        "/(auth)/taikhoan/don-hang-cua-toi/",
        "/(auth)/taikhoan/thong-tin-ca-nhan/",
        "/(auth)/taikhoan/don-hang-cua-toi/thong-tin/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/hoadon/hoadonchitiet",
        "/_authenticated/product/battery",
        "/_authenticated/product/bluetooth",
        "/_authenticated/product/brand",
        "/_authenticated/product/card",
        "/_authenticated/product/category",
        "/_authenticated/product/chip",
        "/_authenticated/product/color",
        "/_authenticated/product/create-product",
        "/_authenticated/product/front-camera",
        "/_authenticated/product/imei",
        "/_authenticated/product/os",
        "/_authenticated/product/ram",
        "/_authenticated/product/rear-camera",
        "/_authenticated/product/resolution",
        "/_authenticated/product/rom",
        "/_authenticated/product/screen",
        "/_authenticated/product/sim",
        "/_authenticated/product/wifi",
        "/_authenticated/voucher/create",
        "/_authenticated/banhang/",
        "/_authenticated/chats/",
        "/_authenticated/dashboard/",
        "/_authenticated/help-center/",
        "/_authenticated/hoadon/",
        "/_authenticated/product/",
        "/_authenticated/quan-ly-lien-he/",
        "/_authenticated/sale/",
        "/_authenticated/voucher/",
        "/_authenticated/product/$id/product-detail",
        "/_authenticated/taikhoan/khachhang/",
        "/_authenticated/taikhoan/nhanvien/"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/reset-password": {
      "filePath": "(auth)/reset-password.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/(auth)/": {
      "filePath": "(auth)/index.lazy.tsx"
    },
    "/(auth)/product/$id": {
      "filePath": "(auth)/product.$id.tsx"
    },
    "/(auth)/tra_cuu_don_hang/thong-tin": {
      "filePath": "(auth)/tra_cuu_don_hang/thong-tin.tsx"
    },
    "/_authenticated/hoadon/hoadonchitiet": {
      "filePath": "_authenticated/hoadon/hoadonchitiet.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/battery": {
      "filePath": "_authenticated/product/battery.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/bluetooth": {
      "filePath": "_authenticated/product/bluetooth.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/brand": {
      "filePath": "_authenticated/product/brand.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/card": {
      "filePath": "_authenticated/product/card.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/category": {
      "filePath": "_authenticated/product/category.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/chip": {
      "filePath": "_authenticated/product/chip.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/color": {
      "filePath": "_authenticated/product/color.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/create-product": {
      "filePath": "_authenticated/product/create-product.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/front-camera": {
      "filePath": "_authenticated/product/front-camera.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/imei": {
      "filePath": "_authenticated/product/imei.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/os": {
      "filePath": "_authenticated/product/os.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/ram": {
      "filePath": "_authenticated/product/ram.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/rear-camera": {
      "filePath": "_authenticated/product/rear-camera.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/resolution": {
      "filePath": "_authenticated/product/resolution.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/rom": {
      "filePath": "_authenticated/product/rom.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/screen": {
      "filePath": "_authenticated/product/screen.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/sim": {
      "filePath": "_authenticated/product/sim.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/wifi": {
      "filePath": "_authenticated/product/wifi.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/voucher/create": {
      "filePath": "_authenticated/voucher/create.tsx",
      "parent": "/_authenticated"
    },
    "/(auth)/dat-hang/payment-result": {
      "filePath": "(auth)/dat-hang/payment-result.lazy.tsx"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/(auth)/dat-hang/": {
      "filePath": "(auth)/dat-hang/index.tsx"
    },
    "/(auth)/taikhoan/": {
      "filePath": "(auth)/taikhoan/index.tsx"
    },
    "/(auth)/chinh-sach-cua-cua-hang/": {
      "filePath": "(auth)/chinh-sach-cua-cua-hang/index.lazy.tsx"
    },
    "/(auth)/dienthoai/": {
      "filePath": "(auth)/dienthoai/index.lazy.tsx"
    },
    "/(auth)/gio-hang/": {
      "filePath": "(auth)/gio-hang/index.lazy.tsx"
    },
    "/(auth)/lien-he/": {
      "filePath": "(auth)/lien-he/index.lazy.tsx"
    },
    "/(auth)/tra_cuu_don_hang/": {
      "filePath": "(auth)/tra_cuu_don_hang/index.lazy.tsx"
    },
    "/_authenticated/banhang/": {
      "filePath": "_authenticated/banhang/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/": {
      "filePath": "_authenticated/dashboard/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/hoadon/": {
      "filePath": "_authenticated/hoadon/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/": {
      "filePath": "_authenticated/product/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/quan-ly-lien-he/": {
      "filePath": "_authenticated/quan-ly-lien-he/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/sale/": {
      "filePath": "_authenticated/sale/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/voucher/": {
      "filePath": "_authenticated/voucher/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/product/$id/product-detail": {
      "filePath": "_authenticated/product/$id.product-detail.tsx",
      "parent": "/_authenticated"
    },
    "/(auth)/taikhoan/don-hang-cua-toi/": {
      "filePath": "(auth)/taikhoan/don-hang-cua-toi/index.tsx"
    },
    "/(auth)/taikhoan/thong-tin-ca-nhan/": {
      "filePath": "(auth)/taikhoan/thong-tin-ca-nhan/index.tsx"
    },
    "/_authenticated/taikhoan/khachhang/": {
      "filePath": "_authenticated/taikhoan/khachhang/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/taikhoan/nhanvien/": {
      "filePath": "_authenticated/taikhoan/nhanvien/index.tsx",
      "parent": "/_authenticated"
    },
    "/(auth)/taikhoan/don-hang-cua-toi/thong-tin/": {
      "filePath": "(auth)/taikhoan/don-hang-cua-toi/thong-tin/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
