-- Quy ước tên database [tên_dự_án hoặc thương hiệu]_[chức_năng hoặc môi_trường]
create database hopestar_store_dev;
use hopestar_store_dev;
CREATE TABLE `product` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`code` VARCHAR(255) NOT NULL UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`description` TEXT(65535),
	`weight` INTEGER,
	`chip_id` INTEGER,
	`brand_id` INTEGER,
	`screen_id` INTEGER,
	`card_id` INTEGER,
	`os_id` INTEGER,
	`charger` VARCHAR(255),
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `chip` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`code` VARCHAR(255) NOT NULL UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `brand` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`code` VARCHAR(255) NOT NULL UNIQUE,
	`name` VARCHAR(255),
	`status` TINYINT,
	`image_url` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `screen` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`code` VARCHAR(255) NOT NULL UNIQUE,
	`type` VARCHAR(255),
	`display_size` DOUBLE,
	`resolution_id` INTEGER,
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `resolution` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`width` DOUBLE,
	`height` DOUBLE,
	`resolution_type` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `card` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`code` VARCHAR(255) UNIQUE,
	`type` VARCHAR(255),
	`capacity` INTEGER,
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `product_sim` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`product_id` INTEGER,
	`sim_id` INTEGER,
	PRIMARY KEY(`id`)
);


CREATE TABLE `sim` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`code` VARCHAR(255),
	`type` VARCHAR(255),
	`sim_multiple` TINYINT,
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `OS` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`product_os_type` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `product_detail` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`price` DECIMAL(24,2),
	`price_sell` DECIMAL(24,2),
	`inventory_quantity` INTEGER,
	`status` TINYINT,
	`color_id` INTEGER,
	`ram_id` INTEGER,
	`rom_id` INTEGER,
	`imei_id` INTEGER,
	`product_id` INTEGER,
	`image_url` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `sale_detail` (
	`sale_id` INTEGER NOT NULL,
	`product_detail_id` INTEGER NOT NULL,
	`effective_price` DECIMAL(24,2),
	PRIMARY KEY(`sale_id`, `product_detail_id`)
);


CREATE TABLE `sale` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`code` VARCHAR(255) UNIQUE,
	`name` VARCHAR(255),
	`date_start` DATETIME,
	`date_end` DATETIME,
	`status` TINYINT,
	`description` VARCHAR(1000),
	`discount_value` DECIMAL(24,2),
	`discount_type` BOOLEAN,
	PRIMARY KEY(`id`)
);


CREATE TABLE `color` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255),
	`description` VARCHAR(1000),
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `ram` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`capacity` INTEGER,
	`description` VARCHAR(1000),
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `rom` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`capacity` INTEGER,
	`description` VARCHAR(1000),
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `imei` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`imei_code` VARCHAR(20),
	`description` VARCHAR(1000),
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `cart_detail` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`quantity` INTEGER,
	`id_product_detail` INTEGER,
	`id_shopping_cart` INTEGER,
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `shopping_cart` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`id_account` INTEGER,
	`code` VARCHAR(255),
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `bill` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`id_cart` INTEGER,
	`id_account` INTEGER,
	`id_voucher` INTEGER,
	`total_price` DECIMAL(24,2),
	`customer_payment` DECIMAL(24,2),
	`amount_change` DECIMAL(24,2),
	`delivery_fee` DECIMAL(24,2),
	`total_due` DECIMAL(24,2),
	`customer_refund` DECIMAL(24,2),
	`discounted_total` DECIMAL(24,2),
	`delivery_date` DATETIME,
	`customer_preferred_date` DATETIME,
	`customer_appointment_ date` DATETIME,
	`receipt_date` DATETIME,
	`payment_date` DATETIME,
	`bill_type` TINYINT,
	`status` TINYINT,
	`address` VARCHAR(255),
	`email` VARCHAR(255),
	`note` VARCHAR(1000),
	`phone` VARCHAR(255),
	`name` VARCHAR(255),
	`created_by` VARCHAR(255),
	`updated_by` VARCHAR(255),
	`payment_id` INTEGER,
	`delivery_id` INTEGER,
	PRIMARY KEY(`id`)
);


CREATE TABLE `account` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`full_name` VARCHAR(255),
	`code` VARCHAR(255) UNIQUE,
	`email` VARCHAR(255) UNIQUE,
	`password` VARCHAR(256),
	`phone` VARCHAR(255),
	`address` VARCHAR(255),
	`google_id` VARCHAR(1000),
	`image_avatar` VARCHAR(255),
	`id_role` INTEGER,
	`gender` BOOLEAN,
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `post` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`title` VARCHAR(255),
	`sumary` TEXT(65535),
	`content` TEXT(65535),
	`image` VARCHAR(255),
	`views` INTEGER,
	`status` TINYINT,
	`id_account` INTEGER,
	`id_category` INTEGER,
	PRIMARY KEY(`id`)
);


CREATE TABLE `role` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`code` VARCHAR(255),
	`name` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `voucher` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`code` VARCHAR(255) UNIQUE,
	`name` VARCHAR(255),
	`condition_price_min` DECIMAL(24,2),
	`condition_price_max` DECIMAL(24,2),
	`discount_value` DECIMAL(24,2),
	`voucher_type` BOOLEAN,
	`quantity` INTEGER,
	`start_time` DATETIME,
	`end_time` DATETIME,
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `article_category` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255),
	`description` VARCHAR(1000),
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `voucher_account` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`id_account` INTEGER,
	`id_voucher` INTEGER,
	PRIMARY KEY(`id`)
);


CREATE TABLE `payment_method` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`method` TINYINT,
	`type` TINYINT,
	`payment_amount` DECIMAL(24,2),
	`description` VARCHAR(255),
	`status` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `delivery_method` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`delivery_type` TINYINT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `bill_detail` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`price` DECIMAL(24,2),
	`quantity` INTEGER,
	`total_price` DECIMAL(24,2),
	`id_product_detail` INTEGER,
	`id_bill` INTEGER,
	`created_by` VARCHAR(255),
	`updated_by` VARCHAR(255),
	PRIMARY KEY(`id`)
);


ALTER TABLE `product`
ADD FOREIGN KEY(`chip_id`) REFERENCES `chip`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `product`
ADD FOREIGN KEY(`brand_id`) REFERENCES `brand`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `product`
ADD FOREIGN KEY(`screen_id`) REFERENCES `screen`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `screen`
ADD FOREIGN KEY(`resolution_id`) REFERENCES `resolution`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `product_sim`
ADD FOREIGN KEY(`product_id`) REFERENCES `product`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `product_sim`
ADD FOREIGN KEY(`sim_id`) REFERENCES `sim`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `product`
ADD FOREIGN KEY(`card_id`) REFERENCES `card`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `product`
ADD FOREIGN KEY(`os_id`) REFERENCES `OS`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `product_detail`
ADD FOREIGN KEY(`color_id`) REFERENCES `color`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `product_detail`
ADD FOREIGN KEY(`ram_id`) REFERENCES `ram`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `product_detail`
ADD FOREIGN KEY(`rom_id`) REFERENCES `rom`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `product_detail`
ADD FOREIGN KEY(`imei_id`) REFERENCES `imei`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `product_detail`
ADD FOREIGN KEY(`product_id`) REFERENCES `product`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `sale_detail`
ADD FOREIGN KEY(`sale_id`) REFERENCES `sale`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `sale_detail`
ADD FOREIGN KEY(`product_detail_id`) REFERENCES `product_detail`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `cart_detail`
ADD FOREIGN KEY(`id_product_detail`) REFERENCES `product_detail`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `cart_detail`
ADD FOREIGN KEY(`id_shopping_cart`) REFERENCES `shopping_cart`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `post`
ADD FOREIGN KEY(`id_account`) REFERENCES `account`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `voucher_account`
ADD FOREIGN KEY(`id_account`) REFERENCES `account`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `voucher_account`
ADD FOREIGN KEY(`id_voucher`) REFERENCES `voucher`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `bill`
ADD FOREIGN KEY(`id_account`) REFERENCES `account`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `bill`
ADD FOREIGN KEY(`id_cart`) REFERENCES `shopping_cart`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `bill`
ADD FOREIGN KEY(`id_voucher`) REFERENCES `voucher`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `bill`
ADD FOREIGN KEY(`delivery_id`) REFERENCES `delivery_method`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `bill`
ADD FOREIGN KEY(`payment_id`) REFERENCES `payment_method`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `bill_detail`
ADD FOREIGN KEY(`id_bill`) REFERENCES `bill`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `bill_detail`
ADD FOREIGN KEY(`id_product_detail`) REFERENCES `product_detail`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `account`
ADD FOREIGN KEY(`id_role`) REFERENCES `role`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `post`
ADD FOREIGN KEY(`id_category`) REFERENCES `article_category`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;



ALTER TABLE account ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE article_category ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE bill ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE bill_detail ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE brand ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE card ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE cart_detail ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE chip ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE color ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE delivery_method ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE imei ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE os ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE payment_method ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE post ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE product ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE product_detail ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE product_sim ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE ram ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE resolution ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE role ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE rom ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE sale ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE sale_detail ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE screen ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE shopping_cart ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE sim ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE voucher ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE voucher_account ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
